# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlfile',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csv/'),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='zone_name',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='zone_no',
            field=models.IntegerField(default=0),
        ),
    ]
